export const SUPPLY_CATEGORIES = [
    { id: 1, name: "Food ingredients", icon: "🌾", slug: "food-ingredients" },
    { id: 2, name: "Beverages", icon: "🥤", slug: "beverages" },
    { id: 3, name: "Fresh produce", icon: "🥦", slug: "fresh-produce" },
    { id: 4, name: "Meat, poultry, and seafood", icon: "🥩", slug: "meat-poultry-seafood" },
    { id: 5, name: "Dairy and eggs", icon: "🧈", slug: "dairy-and-eggs" },
    { id: 6, name: "Dry goods and groceries", icon: "📦", slug: "dry-goods-groceries" },
    { id: 7, name: "Bakery supplies", icon: "🥐", slug: "bakery-supplies" },
    { id: 8, name: "Spices and sauces", icon: "🌶️", slug: "spices-and-sauces" },
    { id: 9, name: "Cooking oil and condiments", icon: "🍾", slug: "cooking-oil-condiments" },
    { id: 10, name: "Packaging and takeaway items", icon: "🛍️", slug: "packaging-takeaway-items" },
    { id: 11, name: "Cleaning supplies", icon: "🧹", slug: "cleaning-supplies" },
    { id: 12, name: "Kitchen equipment", icon: "🍳", slug: "kitchen-equipment" },
    { id: 13, name: "Cooking utensils", icon: "🥄", slug: "cooking-utensils" },
    { id: 14, name: "Tableware and serving items", icon: "🍽️", slug: "tableware-serving-items" },
    { id: 15, name: "Furniture and dining supplies", icon: "🪑", slug: "furniture-dining-supplies" },
    { id: 16, name: "Uniforms and safety equipment", icon: "🥼", slug: "uniforms-safety-equipment" },
    { id: 17, name: "Office and billing supplies", icon: "🖨️", slug: "office-billing-supplies" },
    { id: 18, name: "Maintenance and repair items", icon: "🔧", slug: "maintenance-repair-items" },
    { id: 19, name: "Disposable items", icon: "🥤", slug: "disposable-items" },
    { id: 20, name: "Storage containers and refrigeration supplies", icon: "🧊", slug: "storage-containers-refrigeration" },
];
